#!/bin/sh
# File generated by ocamlbuild

cd /Users/sword/Documents/Paraverif/newParaVerifier-master

rm -f gcd.dll
rm -f max_one_way.dll
rm -f test.dll
# Also clean the script itself
rm -f /Users/sword/Documents/Paraverif/newParaVerifier-master/_build/sanitize.sh
